# Generated by Django 4.0.3 on 2022-04-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img1', models.ImageField(default='', upload_to='upload/')),
                ('slider_img2', models.ImageField(default='', upload_to='upload/')),
                ('slider_img3', models.ImageField(default='', upload_to='upload/')),
                ('slider_img4', models.ImageField(default='', upload_to='upload/')),
            ],
        ),
    ]
