# Generated by Django 4.0.3 on 2022-04-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_slidergallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderGallery',
        ),
    ]
