# Generated by Django 4.0.3 on 2022-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_delete_slidergallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slider_image1', models.ImageField(default='', upload_to='slider_gallery/')),
                ('slider_image2', models.ImageField(default='', upload_to='slider_gallery/')),
                ('slider_image3', models.ImageField(default='', upload_to='slider_gallery/')),
                ('slider_image4', models.ImageField(default='', upload_to='slider_gallery/')),
            ],
        ),
    ]
