# Generated by Django 4.0.3 on 2022-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_sliderimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimage',
            old_name='name',
            new_name='slider_name',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='slider_id',
            field=models.IntegerField(default=0),
        ),
    ]
