# Generated by Django 4.0.3 on 2022-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_slidergallery_delete_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('AC_image', models.ImageField(default='', upload_to='slider_gallery/')),
                ('NAC_image', models.ImageField(default='', upload_to='slider_gallery/')),
                ('DEL_image', models.ImageField(default='', upload_to='slider_gallery/')),
                ('KIN_image', models.ImageField(default='', upload_to='slider_gallery/')),
                ('QUE_image', models.ImageField(default='', upload_to='slider_gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='slidergallery',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
