# Generated by Django 4.0.3 on 2022-04-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimagegallery',
            old_name='DEL_image',
            new_name='DELUXE_image',
        ),
        migrations.RenameField(
            model_name='roomimagegallery',
            old_name='KIN_image',
            new_name='KING_image',
        ),
        migrations.RenameField(
            model_name='roomimagegallery',
            old_name='NAC_image',
            new_name='NON_AC_image',
        ),
        migrations.RenameField(
            model_name='roomimagegallery',
            old_name='QUE_image',
            new_name='QUEEN_image',
        ),
    ]
