# Generated by Django 4.0.3 on 2022-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_rename_del_image_roomimagegallery_deluxe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimagegallery',
            name='AC_image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/No_image_3x4.svg/1280px-No_image_3x4.svg.png', upload_to='slider_gallery/'),
        ),
        migrations.AlterField(
            model_name='roomimagegallery',
            name='DELUXE_image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/No_image_3x4.svg/1280px-No_image_3x4.svg.png', upload_to='slider_gallery/'),
        ),
        migrations.AlterField(
            model_name='roomimagegallery',
            name='KING_image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/No_image_3x4.svg/1280px-No_image_3x4.svg.png', upload_to='slider_gallery/'),
        ),
        migrations.AlterField(
            model_name='roomimagegallery',
            name='NON_AC_image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/No_image_3x4.svg/1280px-No_image_3x4.svg.png', upload_to='slider_gallery/'),
        ),
        migrations.AlterField(
            model_name='roomimagegallery',
            name='QUEEN_image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/No_image_3x4.svg/1280px-No_image_3x4.svg.png', upload_to='slider_gallery/'),
        ),
    ]
