# Generated by Django 4.0.4 on 2022-05-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('SWT', 'Studio with Terrace'), ('DWB', 'Double room with balcony'), ('DWS', 'Double room with share bathroom'), ('DWP', 'Double room with balcony'), ('DWK', 'Double room with kitchen'), ('DUM', 'DUMMY')], max_length=3),
        ),
    ]
