# Generated by Django 4.0.4 on 2022-05-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('SRT', 'Studio Room with Terrace'), ('DRB', 'Double Room with Balcony'), ('DRS', 'Double Room with Shared Bathroom'), ('DRP', 'Double Room with Private Bathroom'), ('DRK', 'Double Room with Kitchen')], max_length=3),
        ),
    ]
